export type PrimaryAttribute = 'strength' | 'agility' | 'intelligence' | 'universal'

export const heroCatalog = [
  { numericId: 1, id: 'anti-mage', key: 'antimage', en: 'Anti-Mage', zh: '敌法师', primaryAttr: 'agility', complexity: 1, mark: 'AM', color: '#72a65b', image: '/heroes/antimage.png' },
  { numericId: 2, id: 'axe', key: 'axe', en: 'Axe', zh: '斧王', primaryAttr: 'strength', complexity: 1, mark: 'A', color: '#c96352', image: '/heroes/axe.png' },
  { numericId: 3, id: 'bane', key: 'bane', en: 'Bane', zh: '祸乱之源', primaryAttr: 'universal', complexity: 2, mark: 'B', color: '#b292cf', image: '/heroes/bane.png' },
  { numericId: 4, id: 'bloodseeker', key: 'bloodseeker', en: 'Bloodseeker', zh: '血魔', primaryAttr: 'agility', complexity: 1, mark: 'B', color: '#72a65b', image: '/heroes/bloodseeker.png' },
  { numericId: 5, id: 'crystal-maiden', key: 'crystal_maiden', en: 'Crystal Maiden', zh: '水晶室女', primaryAttr: 'intelligence', complexity: 1, mark: 'CM', color: '#588fbd', image: '/heroes/crystal_maiden.png' },
  { numericId: 6, id: 'drow-ranger', key: 'drow_ranger', en: 'Drow Ranger', zh: '卓尔游侠', primaryAttr: 'agility', complexity: 1, mark: 'DR', color: '#72a65b', image: '/heroes/drow_ranger.png' },
  { numericId: 7, id: 'earthshaker', key: 'earthshaker', en: 'Earthshaker', zh: '撼地者', primaryAttr: 'strength', complexity: 2, mark: 'E', color: '#c96352', image: '/heroes/earthshaker.png' },
  { numericId: 8, id: 'juggernaut', key: 'juggernaut', en: 'Juggernaut', zh: '主宰', primaryAttr: 'agility', complexity: 1, mark: 'J', color: '#72a65b', image: '/heroes/juggernaut.png' },
  { numericId: 9, id: 'mirana', key: 'mirana', en: 'Mirana', zh: '米拉娜', primaryAttr: 'agility', complexity: 2, mark: 'M', color: '#72a65b', image: '/heroes/mirana.png' },
  { numericId: 11, id: 'shadow-fiend', key: 'nevermore', en: 'Shadow Fiend', zh: '影魔', primaryAttr: 'agility', complexity: 2, mark: 'SF', color: '#72a65b', image: '/heroes/nevermore.png' },
  { numericId: 10, id: 'morphling', key: 'morphling', en: 'Morphling', zh: '变体精灵', primaryAttr: 'agility', complexity: 3, mark: 'M', color: '#72a65b', image: '/heroes/morphling.png' },
  { numericId: 12, id: 'phantom-lancer', key: 'phantom_lancer', en: 'Phantom Lancer', zh: '幻影长矛手', primaryAttr: 'agility', complexity: 2, mark: 'PL', color: '#72a65b', image: '/heroes/phantom_lancer.png' },
  { numericId: 13, id: 'puck', key: 'puck', en: 'Puck', zh: '帕克', primaryAttr: 'intelligence', complexity: 2, mark: 'P', color: '#588fbd', image: '/heroes/puck.png' },
  { numericId: 14, id: 'pudge', key: 'pudge', en: 'Pudge', zh: '帕吉', primaryAttr: 'strength', complexity: 2, mark: 'P', color: '#c96352', image: '/heroes/pudge.png' },
  { numericId: 15, id: 'razor', key: 'razor', en: 'Razor', zh: '雷泽', primaryAttr: 'agility', complexity: 1, mark: 'R', color: '#72a65b', image: '/heroes/razor.png' },
  { numericId: 16, id: 'sand-king', key: 'sand_king', en: 'Sand King', zh: '沙王', primaryAttr: 'universal', complexity: 2, mark: 'SK', color: '#b292cf', image: '/heroes/sand_king.png' },
  { numericId: 17, id: 'storm-spirit', key: 'storm_spirit', en: 'Storm Spirit', zh: '风暴之灵', primaryAttr: 'intelligence', complexity: 2, mark: 'SS', color: '#588fbd', image: '/heroes/storm_spirit.png' },
  { numericId: 18, id: 'sven', key: 'sven', en: 'Sven', zh: '斯温', primaryAttr: 'strength', complexity: 1, mark: 'S', color: '#c96352', image: '/heroes/sven.png' },
  { numericId: 19, id: 'tiny', key: 'tiny', en: 'Tiny', zh: '小小', primaryAttr: 'strength', complexity: 2, mark: 'T', color: '#c96352', image: '/heroes/tiny.png' },
  { numericId: 20, id: 'vengeful-spirit', key: 'vengefulspirit', en: 'Vengeful Spirit', zh: '复仇之魂', primaryAttr: 'agility', complexity: 1, mark: 'VS', color: '#72a65b', image: '/heroes/vengefulspirit.png' },
  { numericId: 21, id: 'windranger', key: 'windrunner', en: 'Windranger', zh: '风行者', primaryAttr: 'universal', complexity: 2, mark: 'W', color: '#b292cf', image: '/heroes/windrunner.png' },
  { numericId: 22, id: 'zeus', key: 'zuus', en: 'Zeus', zh: '宙斯', primaryAttr: 'intelligence', complexity: 1, mark: 'Z', color: '#588fbd', image: '/heroes/zuus.png' },
  { numericId: 23, id: 'kunkka', key: 'kunkka', en: 'Kunkka', zh: '昆卡', primaryAttr: 'strength', complexity: 2, mark: 'K', color: '#c96352', image: '/heroes/kunkka.png' },
  { numericId: 25, id: 'lina', key: 'lina', en: 'Lina', zh: '莉娜', primaryAttr: 'intelligence', complexity: 1, mark: 'L', color: '#588fbd', image: '/heroes/lina.png' },
  { numericId: 31, id: 'lich', key: 'lich', en: 'Lich', zh: '巫妖', primaryAttr: 'intelligence', complexity: 1, mark: 'L', color: '#588fbd', image: '/heroes/lich.png' },
  { numericId: 26, id: 'lion', key: 'lion', en: 'Lion', zh: '莱恩', primaryAttr: 'intelligence', complexity: 1, mark: 'L', color: '#588fbd', image: '/heroes/lion.png' },
  { numericId: 27, id: 'shadow-shaman', key: 'shadow_shaman', en: 'Shadow Shaman', zh: '暗影萨满', primaryAttr: 'intelligence', complexity: 1, mark: 'SS', color: '#588fbd', image: '/heroes/shadow_shaman.png' },
  { numericId: 28, id: 'slardar', key: 'slardar', en: 'Slardar', zh: '斯拉达', primaryAttr: 'strength', complexity: 1, mark: 'S', color: '#c96352', image: '/heroes/slardar.png' },
  { numericId: 29, id: 'tidehunter', key: 'tidehunter', en: 'Tidehunter', zh: '潮汐猎人', primaryAttr: 'strength', complexity: 1, mark: 'T', color: '#c96352', image: '/heroes/tidehunter.png' },
  { numericId: 30, id: 'witch-doctor', key: 'witch_doctor', en: 'Witch Doctor', zh: '巫医', primaryAttr: 'intelligence', complexity: 1, mark: 'WD', color: '#588fbd', image: '/heroes/witch_doctor.png' },
  { numericId: 32, id: 'riki', key: 'riki', en: 'Riki', zh: '力丸', primaryAttr: 'agility', complexity: 1, mark: 'R', color: '#72a65b', image: '/heroes/riki.png' },
  { numericId: 33, id: 'enigma', key: 'enigma', en: 'Enigma', zh: '谜团', primaryAttr: 'universal', complexity: 2, mark: 'E', color: '#b292cf', image: '/heroes/enigma.png' },
  { numericId: 34, id: 'tinker', key: 'tinker', en: 'Tinker', zh: '修补匠', primaryAttr: 'intelligence', complexity: 2, mark: 'T', color: '#588fbd', image: '/heroes/tinker.png' },
  { numericId: 35, id: 'sniper', key: 'sniper', en: 'Sniper', zh: '狙击手', primaryAttr: 'agility', complexity: 1, mark: 'S', color: '#72a65b', image: '/heroes/sniper.png' },
  { numericId: 36, id: 'necrophos', key: 'necrolyte', en: 'Necrophos', zh: '瘟疫法师', primaryAttr: 'intelligence', complexity: 1, mark: 'N', color: '#588fbd', image: '/heroes/necrolyte.png' },
  { numericId: 37, id: 'warlock', key: 'warlock', en: 'Warlock', zh: '术士', primaryAttr: 'intelligence', complexity: 1, mark: 'W', color: '#588fbd', image: '/heroes/warlock.png' },
  { numericId: 38, id: 'beastmaster', key: 'beastmaster', en: 'Beastmaster', zh: '兽王', primaryAttr: 'universal', complexity: 2, mark: 'B', color: '#b292cf', image: '/heroes/beastmaster.png' },
  { numericId: 39, id: 'queen-of-pain', key: 'queenofpain', en: 'Queen of Pain', zh: '痛苦女王', primaryAttr: 'intelligence', complexity: 2, mark: 'QOP', color: '#588fbd', image: '/heroes/queenofpain.png' },
  { numericId: 40, id: 'venomancer', key: 'venomancer', en: 'Venomancer', zh: '剧毒术士', primaryAttr: 'universal', complexity: 1, mark: 'V', color: '#b292cf', image: '/heroes/venomancer.png' },
  { numericId: 41, id: 'faceless-void', key: 'faceless_void', en: 'Faceless Void', zh: '虚空假面', primaryAttr: 'agility', complexity: 2, mark: 'FV', color: '#72a65b', image: '/heroes/faceless_void.png' },
  { numericId: 42, id: 'wraith-king', key: 'skeleton_king', en: 'Wraith King', zh: '冥魂大帝', primaryAttr: 'strength', complexity: 1, mark: 'WK', color: '#c96352', image: '/heroes/skeleton_king.png' },
  { numericId: 43, id: 'death-prophet', key: 'death_prophet', en: 'Death Prophet', zh: '死亡先知', primaryAttr: 'universal', complexity: 1, mark: 'DP', color: '#b292cf', image: '/heroes/death_prophet.png' },
  { numericId: 44, id: 'phantom-assassin', key: 'phantom_assassin', en: 'Phantom Assassin', zh: '幻影刺客', primaryAttr: 'agility', complexity: 1, mark: 'PA', color: '#72a65b', image: '/heroes/phantom_assassin.png' },
  { numericId: 45, id: 'pugna', key: 'pugna', en: 'Pugna', zh: '帕格纳', primaryAttr: 'intelligence', complexity: 2, mark: 'P', color: '#588fbd', image: '/heroes/pugna.png' },
  { numericId: 46, id: 'templar-assassin', key: 'templar_assassin', en: 'Templar Assassin', zh: '圣堂刺客', primaryAttr: 'agility', complexity: 2, mark: 'TA', color: '#72a65b', image: '/heroes/templar_assassin.png' },
  { numericId: 47, id: 'viper', key: 'viper', en: 'Viper', zh: '冥界亚龙', primaryAttr: 'agility', complexity: 1, mark: 'V', color: '#72a65b', image: '/heroes/viper.png' },
  { numericId: 48, id: 'luna', key: 'luna', en: 'Luna', zh: '露娜', primaryAttr: 'agility', complexity: 1, mark: 'L', color: '#72a65b', image: '/heroes/luna.png' },
  { numericId: 49, id: 'dragon-knight', key: 'dragon_knight', en: 'Dragon Knight', zh: '龙骑士', primaryAttr: 'strength', complexity: 1, mark: 'DK', color: '#c96352', image: '/heroes/dragon_knight.png' },
  { numericId: 50, id: 'dazzle', key: 'dazzle', en: 'Dazzle', zh: '戴泽', primaryAttr: 'universal', complexity: 1, mark: 'D', color: '#b292cf', image: '/heroes/dazzle.png' },
  { numericId: 51, id: 'clockwerk', key: 'rattletrap', en: 'Clockwerk', zh: '发条技师', primaryAttr: 'strength', complexity: 2, mark: 'C', color: '#c96352', image: '/heroes/rattletrap.png' },
  { numericId: 52, id: 'leshrac', key: 'leshrac', en: 'Leshrac', zh: '拉席克', primaryAttr: 'intelligence', complexity: 1, mark: 'L', color: '#588fbd', image: '/heroes/leshrac.png' },
  { numericId: 53, id: 'nature-s-prophet', key: 'furion', en: 'Nature\'s Prophet', zh: '自然先知', primaryAttr: 'universal', complexity: 2, mark: 'NSP', color: '#b292cf', image: '/heroes/furion.png' },
  { numericId: 54, id: 'lifestealer', key: 'life_stealer', en: 'Lifestealer', zh: '噬魂鬼', primaryAttr: 'strength', complexity: 2, mark: 'L', color: '#c96352', image: '/heroes/life_stealer.png' },
  { numericId: 55, id: 'dark-seer', key: 'dark_seer', en: 'Dark Seer', zh: '黑暗贤者', primaryAttr: 'intelligence', complexity: 1, mark: 'DS', color: '#588fbd', image: '/heroes/dark_seer.png' },
  { numericId: 56, id: 'clinkz', key: 'clinkz', en: 'Clinkz', zh: '克林克兹', primaryAttr: 'agility', complexity: 2, mark: 'C', color: '#72a65b', image: '/heroes/clinkz.png' },
  { numericId: 57, id: 'omniknight', key: 'omniknight', en: 'Omniknight', zh: '全能骑士', primaryAttr: 'strength', complexity: 1, mark: 'O', color: '#c96352', image: '/heroes/omniknight.png' },
  { numericId: 58, id: 'enchantress', key: 'enchantress', en: 'Enchantress', zh: '魅惑魔女', primaryAttr: 'intelligence', complexity: 2, mark: 'E', color: '#588fbd', image: '/heroes/enchantress.png' },
  { numericId: 59, id: 'huskar', key: 'huskar', en: 'Huskar', zh: '哈斯卡', primaryAttr: 'strength', complexity: 1, mark: 'H', color: '#c96352', image: '/heroes/huskar.png' },
  { numericId: 60, id: 'night-stalker', key: 'night_stalker', en: 'Night Stalker', zh: '暗夜魔王', primaryAttr: 'strength', complexity: 1, mark: 'NS', color: '#c96352', image: '/heroes/night_stalker.png' },
  { numericId: 61, id: 'broodmother', key: 'broodmother', en: 'Broodmother', zh: '育母蜘蛛', primaryAttr: 'agility', complexity: 2, mark: 'B', color: '#72a65b', image: '/heroes/broodmother.png' },
  { numericId: 62, id: 'bounty-hunter', key: 'bounty_hunter', en: 'Bounty Hunter', zh: '赏金猎人', primaryAttr: 'agility', complexity: 1, mark: 'BH', color: '#72a65b', image: '/heroes/bounty_hunter.png' },
  { numericId: 63, id: 'weaver', key: 'weaver', en: 'Weaver', zh: '编织者', primaryAttr: 'agility', complexity: 2, mark: 'W', color: '#72a65b', image: '/heroes/weaver.png' },
  { numericId: 64, id: 'jakiro', key: 'jakiro', en: 'Jakiro', zh: '杰奇洛', primaryAttr: 'intelligence', complexity: 1, mark: 'J', color: '#588fbd', image: '/heroes/jakiro.png' },
  { numericId: 65, id: 'batrider', key: 'batrider', en: 'Batrider', zh: '蝙蝠骑士', primaryAttr: 'universal', complexity: 2, mark: 'B', color: '#b292cf', image: '/heroes/batrider.png' },
  { numericId: 66, id: 'chen', key: 'chen', en: 'Chen', zh: '陈', primaryAttr: 'intelligence', complexity: 3, mark: 'C', color: '#588fbd', image: '/heroes/chen.png' },
  { numericId: 67, id: 'spectre', key: 'spectre', en: 'Spectre', zh: '幽鬼', primaryAttr: 'agility', complexity: 2, mark: 'S', color: '#72a65b', image: '/heroes/spectre.png' },
  { numericId: 69, id: 'doom', key: 'doom_bringer', en: 'Doom', zh: '末日使者', primaryAttr: 'strength', complexity: 2, mark: 'D', color: '#c96352', image: '/heroes/doom_bringer.png' },
  { numericId: 68, id: 'ancient-apparition', key: 'ancient_apparition', en: 'Ancient Apparition', zh: '远古冰魄', primaryAttr: 'intelligence', complexity: 2, mark: 'AA', color: '#588fbd', image: '/heroes/ancient_apparition.png' },
  { numericId: 70, id: 'ursa', key: 'ursa', en: 'Ursa', zh: '熊战士', primaryAttr: 'agility', complexity: 1, mark: 'U', color: '#72a65b', image: '/heroes/ursa.png' },
  { numericId: 71, id: 'spirit-breaker', key: 'spirit_breaker', en: 'Spirit Breaker', zh: '裂魂人', primaryAttr: 'strength', complexity: 1, mark: 'SB', color: '#c96352', image: '/heroes/spirit_breaker.png' },
  { numericId: 72, id: 'gyrocopter', key: 'gyrocopter', en: 'Gyrocopter', zh: '矮人直升机', primaryAttr: 'agility', complexity: 1, mark: 'G', color: '#72a65b', image: '/heroes/gyrocopter.png' },
  { numericId: 73, id: 'alchemist', key: 'alchemist', en: 'Alchemist', zh: '炼金术士', primaryAttr: 'strength', complexity: 1, mark: 'A', color: '#c96352', image: '/heroes/alchemist.png' },
  { numericId: 74, id: 'invoker', key: 'invoker', en: 'Invoker', zh: '祈求者', primaryAttr: 'intelligence', complexity: 3, mark: 'I', color: '#588fbd', image: '/heroes/invoker.png' },
  { numericId: 75, id: 'silencer', key: 'silencer', en: 'Silencer', zh: '沉默术士', primaryAttr: 'intelligence', complexity: 2, mark: 'S', color: '#588fbd', image: '/heroes/silencer.png' },
  { numericId: 76, id: 'outworld-destroyer', key: 'obsidian_destroyer', en: 'Outworld Destroyer', zh: '殁境神蚀者', primaryAttr: 'intelligence', complexity: 2, mark: 'OD', color: '#588fbd', image: '/heroes/obsidian_destroyer.png' },
  { numericId: 77, id: 'lycan', key: 'lycan', en: 'Lycan', zh: '狼人', primaryAttr: 'strength', complexity: 2, mark: 'L', color: '#c96352', image: '/heroes/lycan.png' },
  { numericId: 78, id: 'brewmaster', key: 'brewmaster', en: 'Brewmaster', zh: '酒仙', primaryAttr: 'universal', complexity: 3, mark: 'B', color: '#b292cf', image: '/heroes/brewmaster.png' },
  { numericId: 79, id: 'shadow-demon', key: 'shadow_demon', en: 'Shadow Demon', zh: '暗影恶魔', primaryAttr: 'intelligence', complexity: 2, mark: 'SD', color: '#588fbd', image: '/heroes/shadow_demon.png' },
  { numericId: 80, id: 'lone-druid', key: 'lone_druid', en: 'Lone Druid', zh: '独行德鲁伊', primaryAttr: 'agility', complexity: 3, mark: 'LD', color: '#72a65b', image: '/heroes/lone_druid.png' },
  { numericId: 81, id: 'chaos-knight', key: 'chaos_knight', en: 'Chaos Knight', zh: '混沌骑士', primaryAttr: 'strength', complexity: 1, mark: 'CK', color: '#c96352', image: '/heroes/chaos_knight.png' },
  { numericId: 82, id: 'meepo', key: 'meepo', en: 'Meepo', zh: '米波', primaryAttr: 'agility', complexity: 3, mark: 'M', color: '#72a65b', image: '/heroes/meepo.png' },
  { numericId: 83, id: 'treant-protector', key: 'treant', en: 'Treant Protector', zh: '树精卫士', primaryAttr: 'strength', complexity: 2, mark: 'TP', color: '#c96352', image: '/heroes/treant.png' },
  { numericId: 84, id: 'ogre-magi', key: 'ogre_magi', en: 'Ogre Magi', zh: '食人魔魔法师', primaryAttr: 'strength', complexity: 1, mark: 'OM', color: '#c96352', image: '/heroes/ogre_magi.png' },
  { numericId: 85, id: 'undying', key: 'undying', en: 'Undying', zh: '不朽尸王', primaryAttr: 'strength', complexity: 1, mark: 'U', color: '#c96352', image: '/heroes/undying.png' },
  { numericId: 86, id: 'rubick', key: 'rubick', en: 'Rubick', zh: '拉比克', primaryAttr: 'intelligence', complexity: 3, mark: 'R', color: '#588fbd', image: '/heroes/rubick.png' },
  { numericId: 87, id: 'disruptor', key: 'disruptor', en: 'Disruptor', zh: '干扰者', primaryAttr: 'intelligence', complexity: 2, mark: 'D', color: '#588fbd', image: '/heroes/disruptor.png' },
  { numericId: 88, id: 'nyx-assassin', key: 'nyx_assassin', en: 'Nyx Assassin', zh: '司夜刺客', primaryAttr: 'universal', complexity: 2, mark: 'NA', color: '#b292cf', image: '/heroes/nyx_assassin.png' },
  { numericId: 89, id: 'naga-siren', key: 'naga_siren', en: 'Naga Siren', zh: '娜迦海妖', primaryAttr: 'agility', complexity: 2, mark: 'NS', color: '#72a65b', image: '/heroes/naga_siren.png' },
  { numericId: 90, id: 'keeper-of-the-light', key: 'keeper_of_the_light', en: 'Keeper of the Light', zh: '光之守卫', primaryAttr: 'intelligence', complexity: 2, mark: 'KOT', color: '#588fbd', image: '/heroes/keeper_of_the_light.png' },
  { numericId: 91, id: 'io', key: 'wisp', en: 'Io', zh: '艾欧', primaryAttr: 'universal', complexity: 3, mark: 'I', color: '#b292cf', image: '/heroes/wisp.png' },
  { numericId: 92, id: 'visage', key: 'visage', en: 'Visage', zh: '维萨吉', primaryAttr: 'universal', complexity: 3, mark: 'V', color: '#b292cf', image: '/heroes/visage.png' },
  { numericId: 93, id: 'slark', key: 'slark', en: 'Slark', zh: '斯拉克', primaryAttr: 'agility', complexity: 2, mark: 'S', color: '#72a65b', image: '/heroes/slark.png' },
  { numericId: 94, id: 'medusa', key: 'medusa', en: 'Medusa', zh: '美杜莎', primaryAttr: 'agility', complexity: 1, mark: 'M', color: '#72a65b', image: '/heroes/medusa.png' },
  { numericId: 95, id: 'troll-warlord', key: 'troll_warlord', en: 'Troll Warlord', zh: '巨魔战将', primaryAttr: 'agility', complexity: 2, mark: 'TW', color: '#72a65b', image: '/heroes/troll_warlord.png' },
  { numericId: 96, id: 'centaur-warrunner', key: 'centaur', en: 'Centaur Warrunner', zh: '半人马战行者', primaryAttr: 'strength', complexity: 1, mark: 'CW', color: '#c96352', image: '/heroes/centaur.png' },
  { numericId: 97, id: 'magnus', key: 'magnataur', en: 'Magnus', zh: '马格纳斯', primaryAttr: 'universal', complexity: 2, mark: 'M', color: '#b292cf', image: '/heroes/magnataur.png' },
  { numericId: 98, id: 'timbersaw', key: 'shredder', en: 'Timbersaw', zh: '伐木机', primaryAttr: 'strength', complexity: 2, mark: 'T', color: '#c96352', image: '/heroes/shredder.png' },
  { numericId: 99, id: 'bristleback', key: 'bristleback', en: 'Bristleback', zh: '钢背兽', primaryAttr: 'strength', complexity: 1, mark: 'B', color: '#c96352', image: '/heroes/bristleback.png' },
  { numericId: 100, id: 'tusk', key: 'tusk', en: 'Tusk', zh: '巨牙海民', primaryAttr: 'strength', complexity: 1, mark: 'T', color: '#c96352', image: '/heroes/tusk.png' },
  { numericId: 101, id: 'skywrath-mage', key: 'skywrath_mage', en: 'Skywrath Mage', zh: '天怒法师', primaryAttr: 'intelligence', complexity: 1, mark: 'SM', color: '#588fbd', image: '/heroes/skywrath_mage.png' },
  { numericId: 102, id: 'abaddon', key: 'abaddon', en: 'Abaddon', zh: '亚巴顿', primaryAttr: 'universal', complexity: 1, mark: 'A', color: '#b292cf', image: '/heroes/abaddon.png' },
  { numericId: 103, id: 'elder-titan', key: 'elder_titan', en: 'Elder Titan', zh: '上古巨神', primaryAttr: 'strength', complexity: 2, mark: 'ET', color: '#c96352', image: '/heroes/elder_titan.png' },
  { numericId: 104, id: 'legion-commander', key: 'legion_commander', en: 'Legion Commander', zh: '军团指挥官', primaryAttr: 'strength', complexity: 1, mark: 'LC', color: '#c96352', image: '/heroes/legion_commander.png' },
  { numericId: 106, id: 'ember-spirit', key: 'ember_spirit', en: 'Ember Spirit', zh: '灰烬之灵', primaryAttr: 'agility', complexity: 2, mark: 'ES', color: '#72a65b', image: '/heroes/ember_spirit.png' },
  { numericId: 107, id: 'earth-spirit', key: 'earth_spirit', en: 'Earth Spirit', zh: '大地之灵', primaryAttr: 'strength', complexity: 3, mark: 'ES', color: '#c96352', image: '/heroes/earth_spirit.png' },
  { numericId: 109, id: 'terrorblade', key: 'terrorblade', en: 'Terrorblade', zh: '恐怖利刃', primaryAttr: 'agility', complexity: 2, mark: 'T', color: '#72a65b', image: '/heroes/terrorblade.png' },
  { numericId: 110, id: 'phoenix', key: 'phoenix', en: 'Phoenix', zh: '凤凰', primaryAttr: 'strength', complexity: 2, mark: 'P', color: '#c96352', image: '/heroes/phoenix.png' },
  { numericId: 111, id: 'oracle', key: 'oracle', en: 'Oracle', zh: '神谕者', primaryAttr: 'intelligence', complexity: 3, mark: 'O', color: '#588fbd', image: '/heroes/oracle.png' },
  { numericId: 105, id: 'techies', key: 'techies', en: 'Techies', zh: '工程师', primaryAttr: 'universal', complexity: 2, mark: 'T', color: '#b292cf', image: '/heroes/techies.png' },
  { numericId: 112, id: 'winter-wyvern', key: 'winter_wyvern', en: 'Winter Wyvern', zh: '寒冬飞龙', primaryAttr: 'intelligence', complexity: 2, mark: 'WW', color: '#588fbd', image: '/heroes/winter_wyvern.png' },
  { numericId: 113, id: 'arc-warden', key: 'arc_warden', en: 'Arc Warden', zh: '天穹守望者', primaryAttr: 'universal', complexity: 3, mark: 'AW', color: '#b292cf', image: '/heroes/arc_warden.png' },
  { numericId: 108, id: 'underlord', key: 'abyssal_underlord', en: 'Underlord', zh: '孽主', primaryAttr: 'strength', complexity: 2, mark: 'U', color: '#c96352', image: '/heroes/abyssal_underlord.png' },
  { numericId: 114, id: 'monkey-king', key: 'monkey_king', en: 'Monkey King', zh: '齐天大圣', primaryAttr: 'agility', complexity: 2, mark: 'MK', color: '#72a65b', image: '/heroes/monkey_king.png' },
  { numericId: 120, id: 'pangolier', key: 'pangolier', en: 'Pangolier', zh: '石鳞剑士', primaryAttr: 'universal', complexity: 2, mark: 'P', color: '#b292cf', image: '/heroes/pangolier.png' },
  { numericId: 119, id: 'dark-willow', key: 'dark_willow', en: 'Dark Willow', zh: '邪影芳灵', primaryAttr: 'intelligence', complexity: 2, mark: 'DW', color: '#588fbd', image: '/heroes/dark_willow.png' },
  { numericId: 121, id: 'grimstroke', key: 'grimstroke', en: 'Grimstroke', zh: '天涯墨客', primaryAttr: 'intelligence', complexity: 2, mark: 'G', color: '#588fbd', image: '/heroes/grimstroke.png' },
  { numericId: 129, id: 'mars', key: 'mars', en: 'Mars', zh: '玛尔斯', primaryAttr: 'strength', complexity: 1, mark: 'M', color: '#c96352', image: '/heroes/mars.png' },
  { numericId: 126, id: 'void-spirit', key: 'void_spirit', en: 'Void Spirit', zh: '虚无之灵', primaryAttr: 'universal', complexity: 2, mark: 'VS', color: '#b292cf', image: '/heroes/void_spirit.png' },
  { numericId: 128, id: 'snapfire', key: 'snapfire', en: 'Snapfire', zh: '电炎绝手', primaryAttr: 'universal', complexity: 1, mark: 'S', color: '#b292cf', image: '/heroes/snapfire.png' },
  { numericId: 123, id: 'hoodwink', key: 'hoodwink', en: 'Hoodwink', zh: '森海飞霞', primaryAttr: 'agility', complexity: 2, mark: 'H', color: '#72a65b', image: '/heroes/hoodwink.png' },
  { numericId: 135, id: 'dawnbreaker', key: 'dawnbreaker', en: 'Dawnbreaker', zh: '破晓辰星', primaryAttr: 'strength', complexity: 1, mark: 'D', color: '#c96352', image: '/heroes/dawnbreaker.png' },
  { numericId: 136, id: 'marci', key: 'marci', en: 'Marci', zh: '玛西', primaryAttr: 'universal', complexity: 2, mark: 'M', color: '#b292cf', image: '/heroes/marci.png' },
  { numericId: 137, id: 'primal-beast', key: 'primal_beast', en: 'Primal Beast', zh: '獸', primaryAttr: 'strength', complexity: 1, mark: 'PB', color: '#c96352', image: '/heroes/primal_beast.png' },
  { numericId: 138, id: 'muerta', key: 'muerta', en: 'Muerta', zh: '琼英碧灵', primaryAttr: 'intelligence', complexity: 1, mark: 'M', color: '#588fbd', image: '/heroes/muerta.png' },
  { numericId: 131, id: 'ringmaster', key: 'ringmaster', en: 'Ringmaster', zh: '百戏大王', primaryAttr: 'intelligence', complexity: 2, mark: 'R', color: '#588fbd', image: '/heroes/ringmaster.png' },
  { numericId: 145, id: 'kez', key: 'kez', en: 'Kez', zh: '凯', primaryAttr: 'agility', complexity: 3, mark: 'K', color: '#72a65b', image: '/heroes/kez.png' },
  { numericId: 155, id: 'largo', key: 'largo', en: 'Largo', zh: '朗戈', primaryAttr: 'strength', complexity: 2, mark: 'L', color: '#c96352', image: '/heroes/largo.png' },
] as const

export type HeroId = (typeof heroCatalog)[number]['id']
export type Hero = (typeof heroCatalog)[number]
